let g:codic_token = get(g:, 'codic_token', '')
let g:codic_project_id = get(g:, 'codic_project_id', '')
let g:codic_casing = get(g:, 'codic_casing', '')
let g:codic_acronym_style = get(g:, 'codic_acronym_style', '')
inoremap <expr> <c-e> codic#dialog()
